<!doctype html><html lang="ro"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>{{ $pigeon->label }} · {{ $settings->name }}</title>
<style>
:root{font-family:Arial,sans-serif;color:#182c3d;background:#eef3f7}body{margin:0;padding:24px}main{max-width:1600px;margin:auto;background:#fff;padding:32px;border-radius:12px}header{display:flex;gap:20px;align-items:center;border-bottom:3px solid #1a79be;margin-bottom:24px}header img{max-width:100px;max-height:80px}h1{margin-bottom:8px}h2{font-size:20px}p{white-space:pre-line;line-height:1.5}a{color:#1465a2}nav{display:flex;gap:18px;flex-wrap:wrap;margin-bottom:24px}button{background:#1a79be;color:white;border:0;padding:10px 18px;border-radius:6px;cursor:pointer}.tree{display:flex;min-width:900px;gap:8px}.node{display:flex;gap:8px;flex:1;align-items:stretch}.card{border:1px solid #b6cbda;border-left:3px solid #1a79be;padding:8px;flex:1;display:flex;flex-direction:column;justify-content:center;min-width:110px;overflow-wrap:anywhere;font-size:12px}.parents{display:flex;flex-direction:column;gap:6px;flex:2}.scroll{overflow:auto}.photos{display:flex;gap:16px;flex-wrap:wrap}.photos img{max-height:220px;max-width:300px;object-fit:contain}.muted{color:#687b8a}table{border-collapse:collapse}td,th{padding:8px;text-align:left;border-bottom:1px solid #ddd}
@page{size:A3 landscape;margin:10mm}@media print{body,main{padding:0;background:white}nav,.private-notes,.files{display:none}main{max-width:none}.scroll{overflow:visible}.tree{min-width:0}.card{font-size:9px;min-width:55px;padding:4px}a{color:inherit;text-decoration:none}header{margin-bottom:12px}h1{font-size:22px}}
</style></head><body><main>
<nav><a href="{{ \App\Filament\Resources\Pigeons\PigeonResource::getUrl('index') }}">← Registru</a><a href="{{ \App\Filament\Resources\Pigeons\PigeonResource::getUrl('edit',['record'=>$pigeon]) }}">Editează fișa</a>@foreach([3,4,5] as $d)<a href="?generations={{ $d }}">{{ $d }} generații</a>@endforeach<button onclick="window.print()">Tipărește / salvează PDF</button></nav>
<header>@if($settings->logo)<img src="{{ route('loft.logo') }}" alt="Logo">@endif<div><h1>{{ $settings->name }}</h1><p>{{ $settings->pedigree_header }}</p></div></header>
<h2>{{ $pigeon->label }}</h2><p>{{ ['M'=>'Mascul','F'=>'Femelă','U'=>'Sex necunoscut'][$pigeon->sex] }} · {{ $pigeon->color }} · {{ $pigeon->origin }}</p>
<div class="scroll"><div class="tree">@include('pedigree.node',['node'=>$pigeon,'remaining'=>$depth])</div></div>
@if($pigeon->results)<h2>Rezultate</h2><p>{{ $pigeon->results }}</p>@endif
<section class="files"><h2>Fișiere private</h2><div class="photos">@foreach($pigeon->photos??[] as $i=>$photo)<a href="{{ route('pigeons.file',[$pigeon,'photos',$i]) }}"><img src="{{ route('pigeons.file',[$pigeon,'photos',$i]) }}" alt="Fotografie {{ $i+1 }}"></a>@endforeach</div>@foreach($pigeon->documents??[] as $i=>$document)<p><a href="{{ route('pigeons.file',[$pigeon,'documents',$i]) }}">Descarcă documentul PDF {{ $i+1 }}</a></p>@endforeach</section>
<section class="private-notes"><h2>Note private</h2><p>{{ $pigeon->notes ?: 'Fără note.' }}</p><h2>Istoric stare</h2><table><tr><th>Data</th><th>Din</th><th>În</th></tr>@foreach($history as $event)<tr><td>{{ $event->created_at }}</td><td>{{ \App\Models\Pigeon::STATUSES[$event->from_status]??'Fișă nouă' }}</td><td>{{ \App\Models\Pigeon::STATUSES[$event->to_status] }}</td></tr>@endforeach</table></section>
</main></body></html>